{% set name = "rstcheck-core" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 898bb742e6b1f9a28fb30facb8644fc6d3950b3789d1036ae50c408f191601a2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - poetry
  run:
    - python >=3.8
    - docutils >=0.7
    - importlib-metadata >=1.6,<5.0
    - pydantic >=2
    - typing-extensions >=3.7.4,<5.0

test:
  imports:
    - rstcheck_core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/rstcheck-core
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Checks syntax of reStructuredText and code blocks nested within it
  doc_url: http://rstcheck-core.rtfd.io
  dev_url: https://github.com/rstcheck/rstcheck-core

extra:
  recipe-maintainers:
    - kynan
