{% set name = "rstcheck-core" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2a4ad9e5e772735ea4a766226e7c61bcd0cc9afd7fecb47e8c9328025559ff12

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=61
    - setuptools-scm >=6.2
  run:
    - python >=3.8
    - docutils >=0.7
    - importlib-metadata >=1.6,<5.0
    - pydantic >=2
    - typing-extensions >=3.7.4,<5.0

test:
  imports:
    - rstcheck_core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/rstcheck-core
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Checks syntax of reStructuredText and code blocks nested within it
  doc_url: http://rstcheck-core.rtfd.io
  dev_url: https://github.com/rstcheck/rstcheck-core

extra:
  recipe-maintainers:
    - kynan
