{% set name = "rstcheck-core" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: add19c9a1b97d9087f4b463b49c12cd8a9c03689a255e99089c70a2692f16369

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - docutils >=0.7,<0.19
    - importlib-metadata >=1.6,<5.0
    - pydantic >=1.2,<2.0
    - types-docutils >=0.18,<0.19
    - typing-extensions >=3.7.4,<5.0

test:
  imports:
    - rstcheck_core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/rstcheck-core
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Checks syntax of reStructuredText and code blocks nested within it
  doc_url: http://rstcheck-core.rtfd.io
  dev_url: https://github.com/rstcheck/rstcheck-core

extra:
  recipe-maintainers:
    - kynan
